import { RestaurantState } from '../types';
import { LOCAL_LANDMARK_PINS } from './locationData';

export const INITIAL_RESTAURANT_STATE: RestaurantState = {
  version: 5,
  restaurantNameEn: 'Dogar Sajji & Restaurant',
  restaurantNameUr: 'ڈوگر سجی اینڈ ریسٹورنٹ',
  taglineEn: 'Authentic Balochi Wood-Fired Charcoal Sajji & Traditional Karahi',
  taglineUr: 'روایتی کوئلہ روسٹڈ سجی اور خالص روایتی دیسی دسترخوان',
  hotlineFormatted: '0300-9346628 / 0301-8179528',
  hotlineWhatsappRaw: '923009346628',
  addressEn: 'Main Boulevard, G-Block Commercial, Kasur Road, Lahore, Pakistan',
  addressUr: 'مین بلیوارڈ، جی بلاک کمرشل، قصور روڈ، لاہور، پاکستان',
  timingsEn: '12:00 PM – 02:00 AM (Open 7 Days a Week)',
  timingsUr: 'دوپہر 12:00 بجے تا رات 02:00 بجے (ہفتے کے ساتوں دن کھلا ہے)',
  adminPasswordToken: '12345',
  globalTheme: 'clean-white', // Default clean white canvas #FFFFFF
  activeLightingMode: 'golden-radiance',
  activeBlockScheme: 'block-elevated-card',
  logoImage: '/src/assets/images/dogar_restaurant_logo_1790248394635.jpg',
  heroImage: '/src/assets/images/hero_sajji_roast_banner_1790248382249.jpg',

  menuItems: [
    // =========================================================================
    // GROUP 1: PRIORITY ITEMS (Top of Continuous Stack)
    // Sajji & Chargha Group, Combos/Deals, Cold Drinks
    // EXCLUSION RULE: No Barbecue Rice Varieties (باربی کیو چاول)
    // =========================================================================
    {
      id: 'sajji-full',
      nameEn: 'Full Sajji',
      nameUr: 'فل سجّی',
      categoryId: 'sajji',
      menuGroup: 'priority',
      descriptionEn: 'Traditional whole chicken sajji skewered and wood-charcoal roasted with Balochi mountain rock salts.',
      descriptionUr: 'روایتی کوئلہ روسٹڈ مکمل بلوچی چکن سجی مع خاص مصالحہ جات۔',
      image: '/src/assets/images/dish_chicken_sajji_1790248406038.jpg',
      hasPortions: false,
      prices: { full: 1980 },
      defaultPortion: 'full',
      prepTime: '30 min',
      isPopular: true,
      isSignature: true,
      badge: 'Signature Sajji / خاص سجی',
      isExcludedFastFood: false,
    },
    {
      id: 'sajji-half',
      nameEn: 'Half Sajji',
      nameUr: 'ہاف سجّی',
      categoryId: 'sajji',
      menuGroup: 'priority',
      descriptionEn: 'Half portion of authentic Balochi wood-roasted chicken sajji served hot with fresh lemon cuts.',
      descriptionUr: 'خالص بلوچی لکڑی کے انگاروں پر پکی ہوئی آدھی چکن سجی مع لیموں اور مصالحہ۔',
      image: '/src/assets/images/dish_chicken_sajji_1790248406038.jpg',
      hasPortions: false,
      prices: { full: 1050 },
      defaultPortion: 'full',
      prepTime: '25 min',
      isPopular: true,
      badge: 'Popular Choice / مقبول سجی',
      isExcludedFastFood: false,
    },
    {
      id: 'sajji-quarter',
      nameEn: 'Quarter Sajji',
      nameUr: 'پاؤ سجّی',
      categoryId: 'sajji',
      menuGroup: 'priority',
      descriptionEn: 'Single-serving quarter chicken sajji freshly cut from the woodfire pit.',
      descriptionUr: 'انگاروں سے تازہ اتاری گئی ایک فرد کے لیے مخصوص پاؤ چکن سجی۔',
      image: '/src/assets/images/dish_chicken_sajji_1790248406038.jpg',
      hasPortions: false,
      prices: { full: 650 },
      defaultPortion: 'full',
      prepTime: '20 min',
      badge: 'Single Serving / سنگل سجی',
      isExcludedFastFood: false,
    },
    {
      id: 'chargha-full',
      nameEn: 'Full Chargha',
      nameUr: 'فل چکن چرخہ',
      categoryId: 'sajji',
      menuGroup: 'priority',
      descriptionEn: 'Deep-steamed and crisp golden whole chicken chargha marinated in hand-ground Lahori spices.',
      descriptionUr: 'خالص لاہوری مصالحوں اور لیموں کے عرق سے تیار شدہ مکمل چکن چرخہ۔',
      image: '/src/assets/images/dish_chicken_sajji_1790248406038.jpg',
      hasPortions: false,
      prices: { full: 1600 },
      defaultPortion: 'full',
      prepTime: '25 min',
      isPopular: true,
      badge: 'Traditional / روایتی چرخہ',
      isExcludedFastFood: false,
    },
    {
      id: 'chargha-half',
      nameEn: 'Half Chargha',
      nameUr: 'ہاف چکن چرخہ',
      categoryId: 'sajji',
      menuGroup: 'priority',
      descriptionEn: 'Crispy seasoned half portion chicken chargha seasoned with special lemon masala.',
      descriptionUr: 'چٹپٹے مصالحوں سے تیار شدہ آدھا چکن چرخہ۔',
      image: '/src/assets/images/dish_chicken_sajji_1790248406038.jpg',
      hasPortions: false,
      prices: { full: 800 },
      defaultPortion: 'full',
      prepTime: '20 min',
      badge: 'Crispy / کرسپی چرخہ',
      isExcludedFastFood: false,
    },
    {
      id: 'rice-plate-full',
      nameEn: 'Full Rice Plate',
      nameUr: 'فل چاول پلیٹ',
      categoryId: 'sajji',
      menuGroup: 'priority',
      descriptionEn: 'Fragrant long-grain spiced aromatic rice plate, the authentic accompaniment to hot sajji.',
      descriptionUr: 'خوشبودار روایتی مصالحہ دار سجی چاول کی بڑی پلیٹ۔',
      image: '/src/assets/images/dish_kabuli_pulao_1790248455916.jpg',
      hasPortions: false,
      prices: { full: 450 },
      defaultPortion: 'full',
      prepTime: '10 min',
      badge: 'Aromatic Rice / خاص چاول',
      isExcludedFastFood: false,
    },
    {
      id: 'rice-plate-half',
      nameEn: 'Half Rice Plate',
      nameUr: 'ہاف چاول پلیٹ',
      categoryId: 'sajji',
      menuGroup: 'priority',
      descriptionEn: 'Half portion of seasoned aromatic rice plate cooked in traditional broth.',
      descriptionUr: 'سجی کے ساتھ مخصوص خوشبودار چاول کی آدھی پلیٹ۔',
      image: '/src/assets/images/dish_kabuli_pulao_1790248455916.jpg',
      hasPortions: false,
      prices: { full: 250 },
      defaultPortion: 'full',
      prepTime: '10 min',
      badge: 'Single Portion / ہاف پلیٹ',
      isExcludedFastFood: false,
    },
    {
      id: 'deal-01',
      nameEn: 'Deal 01',
      nameUr: 'ڈیل 01',
      categoryId: 'combos',
      menuGroup: 'priority',
      descriptionEn: 'Includes 2 Beef Kababs, 1 Roghni Naan, 1 Soft Drink Can.',
      descriptionUr: 'خصوصی ڈیل 01: 2 بیف کباب، 1 روغنی نان، اور 1 ریگولر سوفٹ ڈرنک کین۔',
      image: '/src/assets/images/dish_combo_feast_1790249210676.jpg',
      hasPortions: false,
      prices: { full: 1280 },
      defaultPortion: 'full',
      prepTime: '20 min',
      isPopular: true,
      badge: 'Special Deal (Rs. 1280)',
      isExcludedFastFood: false,
    },
    {
      id: 'deal-02',
      nameEn: 'Deal 02',
      nameUr: 'ڈیل 02',
      categoryId: 'combos',
      menuGroup: 'priority',
      descriptionEn: 'Includes 1 Full Chicken Sajji, 2 Large Soft Drinks, Salad & Raita Bucket.',
      descriptionUr: 'میگا ڈیل 02: 1 مکمل بلوچی چکن سجی، 2 بڑی بوتلیں کولڈ ڈرنک، سلاد و رائتہ۔',
      image: '/src/assets/images/dish_combo_feast_1790249210676.jpg',
      hasPortions: false,
      prices: { full: 1980 },
      defaultPortion: 'full',
      prepTime: '25 min',
      isPopular: true,
      isSignature: true,
      badge: 'Mega Deal (Rs. 1980)',
      isExcludedFastFood: false,
    },
    {
      id: 'drink-regular-soft-drink',
      nameEn: 'Regular Soft Drink',
      nameUr: 'ریگولر کولڈ ڈرنک',
      categoryId: 'drinks',
      menuGroup: 'priority',
      descriptionEn: 'Chilled 250ml soda bottle or can (Coke / Sprite / Fanta / Pakola).',
      descriptionUr: 'ٹھنڈا ریگولر 250 ملی کولڈ ڈرنک (کوکا کولا، سپرائٹ، فانٹا)۔',
      image: '/src/assets/images/dish_beverages_ice_1790248491563.jpg',
      hasPortions: false,
      prices: { full: 100 },
      defaultPortion: 'full',
      prepTime: 'Chilled / ٹھنڈا',
      isPopular: false,
      isExcludedFastFood: false,
    },
    {
      id: 'drink-half-litre',
      nameEn: 'Half Litre',
      nameUr: 'آدھا لیٹر بوتل',
      categoryId: 'drinks',
      menuGroup: 'priority',
      descriptionEn: 'Chilled 500ml beverage bottle.',
      descriptionUr: 'ٹھنڈی 500 ملی لیٹر بوتل۔',
      image: '/src/assets/images/dish_beverages_ice_1790248491563.jpg',
      hasPortions: false,
      prices: { full: 110 },
      defaultPortion: 'full',
      prepTime: 'Chilled / ٹھنڈا',
      isPopular: false,
      isExcludedFastFood: false,
    },
    {
      id: 'drink-15-litre-jumbo',
      nameEn: '1.5L Jumbo',
      nameUr: 'ڈیڑھ لیٹر جمبو بوتل',
      categoryId: 'drinks',
      menuGroup: 'priority',
      descriptionEn: '1.5 Litre family size cold beverage bottle.',
      descriptionUr: 'ڈیڑھ لیٹر فیملی سائز بوتل۔',
      image: '/src/assets/images/dish_beverages_ice_1790248491563.jpg',
      hasPortions: false,
      prices: { full: 220 },
      defaultPortion: 'full',
      prepTime: 'Chilled / ٹھنڈا',
      isPopular: true,
      badge: 'Family Size / فیملی بوتل',
      isExcludedFastFood: false,
    },
    {
      id: 'drink-mineral-water-large',
      nameEn: 'Mineral Water Large',
      nameUr: 'منرل واٹر (بڑا)',
      categoryId: 'drinks',
      menuGroup: 'priority',
      descriptionEn: 'Pure chilled 1.5L bottled mineral drinking water.',
      descriptionUr: 'صاف اور شفاف ٹھنڈا 1.5 لیٹر منرل واٹر۔',
      image: '/src/assets/images/dish_beverages_ice_1790248491563.jpg',
      hasPortions: false,
      prices: { full: 100 },
      defaultPortion: 'full',
      prepTime: 'Chilled / ٹھنڈا',
      isPopular: false,
      isExcludedFastFood: false,
    },
    {
      id: 'drink-mineral-water-small',
      nameEn: 'Small Mineral Water',
      nameUr: 'منرل واٹر (چھوٹا)',
      categoryId: 'drinks',
      menuGroup: 'priority',
      descriptionEn: 'Pure chilled 500ml bottled mineral drinking water.',
      descriptionUr: '500 ملی لیٹر صاف شفاف ٹھنڈا منرل واٹر۔',
      image: '/src/assets/images/dish_beverages_ice_1790248491563.jpg',
      hasPortions: false,
      prices: { full: 60 },
      defaultPortion: 'full',
      prepTime: 'Chilled / ٹھنڈا',
      isPopular: false,
      isExcludedFastFood: false,
    },

    // =========================================================================
    // GROUP 2: EXTENDED CATALOG (Page 2 Continuous Stream)
    // Premium Desi Karahi, Mutton, Beef, Chicken Karahi, BBQ, Daal, Tandoor
    // =========================================================================

    // --- Premium Desi Karahi Matrix ---
    {
      id: 'karahi-desi-murgh',
      nameEn: 'Desi Murgh Karahi',
      nameUr: 'دیسی مرغ کڑاہی',
      categoryId: 'karahi',
      menuGroup: 'extended',
      descriptionEn: 'Fresh authentic desi chicken wok prepared in pure desi ghee with fresh vine tomatoes, julienned ginger, and green chillies.',
      descriptionUr: 'اصلی دیسی مرغ کڑاہی خالص دیسی گھی، ٹماٹر اور ہری مرچوں میں تیار شدہ۔',
      image: '/src/assets/images/dish_karahi_special_1790248428097.jpg',
      hasPortions: true,
      prices: { full: 3400, half: 1750 },
      defaultPortion: 'full',
      prepTime: '30-35 min',
      isPopular: true,
      isSignature: true,
      badge: 'Desi Ghee / خالص دیسی گھی',
      isExcludedFastFood: false,
    },
    {
      id: 'karahi-desi-murgh-achari',
      nameEn: 'Desi Murgh Achari',
      nameUr: 'دیسی مرغ اچاری',
      categoryId: 'karahi',
      menuGroup: 'extended',
      descriptionEn: 'Authentic desi chicken cooked with mustard seeds, kalonji, crushed fennel, and traditional pickled spices.',
      descriptionUr: 'اصلی دیسی مرغ اچاری مصالحوں اور کلونجی کے تڑکے کے ساتھ تیار۔',
      image: '/src/assets/images/dish_karahi_special_1790248428097.jpg',
      hasPortions: true,
      prices: { full: 3500, half: 1800 },
      defaultPortion: 'full',
      prepTime: '30-35 min',
      badge: 'Tangy Achari / چٹپٹا اچاری',
      isExcludedFastFood: false,
    },
    {
      id: 'karahi-desi-murgh-makhni',
      nameEn: 'Desi Murgh Makhni',
      nameUr: 'دیسی مرغ مکھنی',
      categoryId: 'karahi',
      menuGroup: 'extended',
      descriptionEn: 'Tender desi chicken enriched with pure country butter, fresh dairy cream, and mild aromatic herbs.',
      descriptionUr: 'خالص مکھن اور بالائی میں دم پخت دیسی مرغ مکھنی کڑاہی۔',
      image: '/src/assets/images/dish_karahi_special_1790248428097.jpg',
      hasPortions: true,
      prices: { full: 3500, half: 1900 },
      defaultPortion: 'full',
      prepTime: '35 min',
      isPopular: true,
      badge: 'Country Butter / مکھنی خاص',
      isExcludedFastFood: false,
    },

    // --- Premium Mutton Matrix ---
    {
      id: 'mutton-karahi',
      nameEn: 'Mutton Karahi',
      nameUr: 'مٹن کڑاہی خاص',
      categoryId: 'mutton',
      menuGroup: 'extended',
      descriptionEn: 'Fresh daily halal slaughter mutton cooked in cast-iron wok with fresh tomatoes, ginger juliennes, and black pepper.',
      descriptionUr: 'روزانہ تازہ ذبیحہ مٹن کڑاہی، ٹماٹر اور تازہ مصالحوں کے ساتھ لوہے کی کڑاہی میں تیار۔',
      image: '/src/assets/images/dish_mutton_sajji_1790248417867.jpg',
      hasPortions: true,
      prices: { full: 3500, half: 1900 },
      defaultPortion: 'full',
      prepTime: '35-40 min',
      isPopular: true,
      isSignature: true,
      badge: 'Chef Choice / خاص مٹن',
      isExcludedFastFood: false,
    },
    {
      id: 'mutton-achari',
      nameEn: 'Mutton Achari',
      nameUr: 'مٹن اچاری',
      categoryId: 'mutton',
      menuGroup: 'extended',
      descriptionEn: 'Succulent prime mutton pieces simmered in zesty pickle spices, nigella seeds, and slit green chillies.',
      descriptionUr: 'روایتی اچاری مصالحوں اور ہری مرچوں میں بنی خوش ذائقہ مٹن اچاری۔',
      image: '/src/assets/images/dish_mutton_sajji_1790248417867.jpg',
      hasPortions: true,
      prices: { full: 3500, half: 1800 },
      defaultPortion: 'full',
      prepTime: '35-40 min',
      badge: 'Pickled Spice / مٹن اچاری',
      isExcludedFastFood: false,
    },
    {
      id: 'mutton-makhni',
      nameEn: 'Mutton Makhni',
      nameUr: 'مٹن مکھنی',
      categoryId: 'mutton',
      menuGroup: 'extended',
      descriptionEn: 'Slow-simmered tender mutton cubes smothered in velvet pure desi butter and thick farm cream.',
      descriptionUr: 'خالص دیسی مکھن اور کریم میں تیار مٹن مکھنی کڑاہی۔',
      image: '/src/assets/images/dish_mutton_sajji_1790248417867.jpg',
      hasPortions: true,
      prices: { full: 3500, half: 1950 },
      defaultPortion: 'full',
      prepTime: '40 min',
      isPopular: true,
      badge: 'Butter Mutton / شاہی مکھنی',
      isExcludedFastFood: false,
    },

    // --- Premium Beef Matrix ---
    {
      id: 'beef-kabab-plate',
      nameEn: 'Beef Kabab Plate',
      nameUr: 'بیف کباب پلیٹ',
      categoryId: 'beef',
      menuGroup: 'extended',
      descriptionEn: 'Traditional beef seekh kababs charcoal-grilled over acacia coals, served with mint raita and onion rings.',
      descriptionUr: 'تازہ کوئلوں پر پکے ہوئے بیف کباب مع پودینہ رائتہ و پیاز سلاد۔',
      image: '/src/assets/images/dish_beef_bihari_1790249187284.jpg',
      hasPortions: true,
      prices: { full: 2350, half: 1250 },
      defaultPortion: 'full',
      prepTime: '20 min',
      isPopular: true,
      badge: 'Charcoal Grilled / سیخ کباب',
      isExcludedFastFood: false,
    },
    {
      id: 'beef-tikka-boti',
      nameEn: 'Beef Tikka Boti',
      nameUr: 'بیف تکہ بوٹی',
      categoryId: 'beef',
      menuGroup: 'extended',
      descriptionEn: 'Tender beef chunks marinated in raw papaya and traditional roasted spices, slow-grilled on skewers.',
      descriptionUr: 'کچے پپیتے اور روایتی مصالحوں میں گلی ہوئی نرم بیف تکہ بوٹی۔',
      image: '/src/assets/images/dish_beef_bihari_1790249187284.jpg',
      hasPortions: true,
      prices: { full: 2350, half: 1250 },
      defaultPortion: 'full',
      prepTime: '25 min',
      badge: 'Tender Boti / نرم بوٹی',
      isExcludedFastFood: false,
    },
    {
      id: 'beef-khamiri-kabab',
      nameEn: 'Beef Khamiri Kabab',
      nameUr: 'بیف خمیری کباب',
      categoryId: 'beef',
      menuGroup: 'extended',
      descriptionEn: 'Signature spiced fermented dough marinated beef kabab patties with authentic heritage charcoal aroma.',
      descriptionUr: 'روایتی خمیری مصالحہ جات میں تیار بیف خمیری کباب۔',
      image: '/src/assets/images/dish_beef_bihari_1790249187284.jpg',
      hasPortions: true,
      prices: { full: 2250, half: 1150 },
      defaultPortion: 'full',
      prepTime: '20 min',
      badge: 'Heritage Recipe / خمیری کباب',
      isExcludedFastFood: false,
    },
    {
      id: 'beef-roll',
      nameEn: 'Beef Roll',
      nameUr: 'بیف رول',
      categoryId: 'beef',
      menuGroup: 'extended',
      descriptionEn: 'Juicy grilled beef seekh or boti wrapped in crispy tandoor paratha with onions and green herb sauce.',
      descriptionUr: 'تازہ پراٹھا میں لپٹا ہوا ذائقہ دار بیف سیخ کباب رول۔',
      image: '/src/assets/images/dish_beef_bihari_1790249187284.jpg',
      hasPortions: true,
      prices: { full: 2500, half: 1300 },
      defaultPortion: 'full',
      prepTime: '15 min',
      isPopular: true,
      badge: 'Paratha Roll / بیف رول',
      isExcludedFastFood: false,
    },

    // --- Chicken Curries & Karahi Matrix ---
    {
      id: 'chicken-shinwari',
      nameEn: 'Chicken Shinwari',
      nameUr: 'چکن شنواری کڑاہی',
      categoryId: 'karahi',
      menuGroup: 'extended',
      descriptionEn: 'Authentic Pashtun-style karahi cooked solely with chicken, salt, ripe tomatoes, and green chillies in pure desi ghee.',
      descriptionUr: 'خالص پختون طرز شنواری چکن کڑاہی صرف نمک، ٹماٹر اور ہری مرچوں کے ساتھ۔',
      image: '/src/assets/images/dish_karahi_special_1790248428097.jpg',
      hasPortions: true,
      prices: { full: 1900, half: 1000 },
      defaultPortion: 'full',
      prepTime: '25-30 min',
      isPopular: true,
      isSignature: true,
      badge: 'Shinwari Authentic / اصل شنواری',
      isExcludedFastFood: false,
    },
    {
      id: 'chicken-ginger',
      nameEn: 'Chicken Ginger',
      nameUr: 'چکن جنجر کڑاہی',
      categoryId: 'karahi',
      menuGroup: 'extended',
      descriptionEn: 'Boneless chicken cubes simmered with generous julienned ginger, cracked coriander, and rich thick gravy.',
      descriptionUr: 'ادرک کے لچھوں اور خوشبودار مصالحوں میں بنی چکن جنجر۔',
      image: '/src/assets/images/dish_karahi_special_1790248428097.jpg',
      hasPortions: true,
      prices: { full: 1800, half: 950 },
      defaultPortion: 'full',
      prepTime: '25 min',
      badge: 'Fresh Ginger / تازہ ادرک',
      isExcludedFastFood: false,
    },
    {
      id: 'chicken-makhni',
      nameEn: 'Chicken Makhni',
      nameUr: 'چکن مکھنی ہانڈی',
      categoryId: 'karahi',
      menuGroup: 'extended',
      descriptionEn: 'Silky boneless chicken cooked in clay handi with farm butter, dairy cream, and kasuri methi.',
      descriptionUr: 'دیسی مکھن، بالائی اور قصوری میتھی کے ساتھ تیار نرم چکن مکھنی ہانڈی۔',
      image: '/src/assets/images/dish_karahi_special_1790248428097.jpg',
      hasPortions: true,
      prices: { full: 1600, half: 800 },
      defaultPortion: 'full',
      prepTime: '25 min',
      isPopular: true,
      badge: 'Butter Handi / مکھنی ہانڈی',
      isExcludedFastFood: false,
    },
    {
      id: 'chicken-white',
      nameEn: 'Chicken White',
      nameUr: 'چکن وائٹ کڑاہی',
      categoryId: 'karahi',
      menuGroup: 'extended',
      descriptionEn: 'Mild, luscious chicken karahi made with thick beaten yogurt, heavy dairy cream, and roasted white cumin.',
      descriptionUr: 'دہی، سفید زیرہ اور کریم کے ساتھ بنائی گئی لذیذ چکن وائٹ کڑاہی۔',
      image: '/src/assets/images/dish_karahi_special_1790248428097.jpg',
      hasPortions: true,
      prices: { full: 1650, half: 850 },
      defaultPortion: 'full',
      prepTime: '25 min',
      badge: 'White Cream / وائٹ کڑاہی',
      isExcludedFastFood: false,
    },
    {
      id: 'chicken-green',
      nameEn: 'Chicken Green',
      nameUr: 'چکن گرین کڑاہی',
      categoryId: 'karahi',
      menuGroup: 'extended',
      descriptionEn: 'Vibrant green herb karahi infused with fresh coriander, garden mint, and roasted green chillies.',
      descriptionUr: 'ہرا دھنیا، پودینہ اور ہری مرچوں کے پسے ہوئے پیسٹ میں تیار چکن گرین کڑاہی۔',
      image: '/src/assets/images/dish_karahi_special_1790248428097.jpg',
      hasPortions: true,
      prices: { full: 1600, half: 800 },
      defaultPortion: 'full',
      prepTime: '25 min',
      badge: 'Herbal Green / ہری کڑاہی',
      isExcludedFastFood: false,
    },
    {
      id: 'chicken-black-pepper',
      nameEn: 'Chicken Black Pepper',
      nameUr: 'چکن بلیک پیپر کڑاہی',
      categoryId: 'karahi',
      menuGroup: 'extended',
      descriptionEn: 'Robust wok curry seasoned with freshly crushed Malabar black peppercorns and roasted garlic cloves.',
      descriptionUr: 'تازہ پسی کالی مرچ اور لہسن کے ساتھ تیار چکن بلیک پیپر کڑاہی۔',
      image: '/src/assets/images/dish_karahi_special_1790248428097.jpg',
      hasPortions: true,
      prices: { full: 1800, half: 900 },
      defaultPortion: 'full',
      prepTime: '25 min',
      badge: 'Black Pepper / کالی مرچ',
      isExcludedFastFood: false,
    },

    // --- Charcoal Kabab & Boti Matrix ---
    {
      id: 'chicken-seekh-kabab',
      nameEn: 'Chicken Seekh Kabab',
      nameUr: 'چکن سیخ کباب',
      categoryId: 'bbq',
      menuGroup: 'extended',
      descriptionEn: 'Finely minced seasoned chicken skewered and roasted to juicy perfection over live coals.',
      descriptionUr: 'انگاروں پر پکے ہوئے رسیلے اور لذیذ چکن سیخ کباب۔',
      image: '/src/assets/images/dish_bbq_tikka_1790248468259.jpg',
      hasPortions: true,
      prices: { full: 560, half: 280 },
      defaultPortion: 'full',
      prepTime: '15-20 min',
      isPopular: true,
      badge: 'Charcoal BBQ / سیخ کباب',
      isExcludedFastFood: false,
    },
    {
      id: 'chicken-reshmi-kabab',
      nameEn: 'Chicken Reshmi Kabab',
      nameUr: 'چکن ریشمی کباب',
      categoryId: 'bbq',
      menuGroup: 'extended',
      descriptionEn: 'Silky melt-in-mouth chicken mince kababs blended with cream, cheese, and mild white pepper.',
      descriptionUr: 'بالائی اور مکھن میں گھلے ریشم جیسے نرم چکن ریشمی کباب۔',
      image: '/src/assets/images/dish_bbq_tikka_1790248468259.jpg',
      hasPortions: true,
      prices: { full: 640, half: 320 },
      defaultPortion: 'full',
      prepTime: '20 min',
      badge: 'Melt-in-Mouth / ریشمی کباب',
      isExcludedFastFood: false,
    },
    {
      id: 'chicken-boti-plate',
      nameEn: 'Chicken Boti Plate',
      nameUr: 'چکن بوٹی پلیٹ',
      categoryId: 'bbq',
      menuGroup: 'extended',
      descriptionEn: 'Boneless chicken cubes spiced with traditional tandoori marinade and skewered over embers.',
      descriptionUr: 'کوئلوں پر سینکی ہوئی چٹپٹی چکن بوٹی کی پلیٹ۔',
      image: '/src/assets/images/dish_bbq_tikka_1790248468259.jpg',
      hasPortions: true,
      prices: { full: 700, half: 350 },
      defaultPortion: 'full',
      prepTime: '20 min',
      isPopular: true,
      badge: 'Tandoori Boti / چکن بوٹی',
      isExcludedFastFood: false,
    },
    {
      id: 'malai-boti-plate',
      nameEn: 'Malai Boti Plate',
      nameUr: 'ملائی بوٹی پلیٹ',
      categoryId: 'bbq',
      menuGroup: 'extended',
      descriptionEn: 'Tender chicken cubes bathed in heavy cream, yogurt, cardamoms, and mild green chillies.',
      descriptionUr: 'کریم اور الائچی کے عرق میں تیار انتہائی نرم ملائی بوٹی پلیٹ۔',
      image: '/src/assets/images/dish_bbq_tikka_1790248468259.jpg',
      hasPortions: true,
      prices: { full: 800, half: 400 },
      defaultPortion: 'full',
      prepTime: '20 min',
      isPopular: true,
      badge: 'Creamy Malai / ملائی بوٹی',
      isExcludedFastFood: false,
    },
    {
      id: 'chicken-tikka-piece',
      nameEn: 'Chicken Tikka Piece',
      nameUr: 'چکن تکہ پیس',
      categoryId: 'bbq',
      menuGroup: 'extended',
      descriptionEn: 'Classic charcoal-roasted quarter chicken tikka piece (Leg or Breast) with spicy chatpata marinade.',
      descriptionUr: 'روایتی انگاروں پر سینکا ہوا چکن تکہ پیس مع لیموں اور چٹنی۔',
      image: '/src/assets/images/dish_bbq_tikka_1790248468259.jpg',
      hasPortions: false,
      prices: { full: 280 },
      defaultPortion: 'full',
      prepTime: '15-20 min',
      isPopular: true,
      badge: 'Charcoal Tikka / چکن تکہ',
      isExcludedFastFood: false,
    },
    {
      id: 'gola-kabab-plate',
      nameEn: 'Gola Kabab Plate',
      nameUr: 'گولا کباب پلیٹ',
      categoryId: 'bbq',
      menuGroup: 'extended',
      descriptionEn: 'Round succulent spiced kababs marinated with onion water, nutmeg, and aromatic garam masala.',
      descriptionUr: 'انتہائی جوسی اور نرم گول گولا کباب کی خصوصی پلیٹ۔',
      image: '/src/assets/images/dish_bbq_tikka_1790248468259.jpg',
      hasPortions: true,
      prices: { full: 480, half: 240 },
      defaultPortion: 'full',
      prepTime: '15 min',
      badge: 'Juicy Gola / گولا کباب',
      isExcludedFastFood: false,
    },

    // --- Daal & Vegetables Matrix ---
    {
      id: 'daal-fry-makhni',
      nameEn: 'Daal Fry Makhni',
      nameUr: 'دال فرائی مکھنی',
      categoryId: 'daal',
      menuGroup: 'extended',
      descriptionEn: 'Slow-simmered yellow lentils tempered in pure country butter, cumin, and whole roasted chillies.',
      descriptionUr: 'دیسی مکھن اور زیرہ کے کڑکے سے تیار شدہ دال فرائی مکھنی۔',
      image: '/src/assets/images/dish_daal_makhni_1790249173685.jpg',
      hasPortions: true,
      prices: { full: 200, half: 120 },
      defaultPortion: 'full',
      prepTime: '15 min',
      isPopular: true,
      badge: 'Desi Butter / مکھن تڑکہ',
      isExcludedFastFood: false,
    },
    {
      id: 'daal-chana-fry',
      nameEn: 'Daal Chana Fry',
      nameUr: 'دال چنا فرائی',
      categoryId: 'daal',
      menuGroup: 'extended',
      descriptionEn: 'Gram lentils cooked to tender perfection with golden onions, tomatoes, and garam masala tadka.',
      descriptionUr: 'پیاز اور ٹماٹروں کے شاندار تڑکے کے ساتھ بنی دال چنا فرائی۔',
      image: '/src/assets/images/dish_daal_makhni_1790249173685.jpg',
      hasPortions: true,
      prices: { full: 250, half: 150 },
      defaultPortion: 'full',
      prepTime: '15 min',
      badge: 'Chana Tadka / دال چنا',
      isExcludedFastFood: false,
    },
    {
      id: 'daal-mash-fry',
      nameEn: 'Daal Mash Fry',
      nameUr: 'دال ماش فرائی',
      categoryId: 'daal',
      menuGroup: 'extended',
      descriptionEn: 'White urad lentils cooked dry-style with crispy browned onions, sliced ginger, and fresh green chillies.',
      descriptionUr: 'کھڑی اور بھنی ہوئی دال ماش فرائی مع ادرک اور ہرا دھنیا۔',
      image: '/src/assets/images/dish_daal_makhni_1790249173685.jpg',
      hasPortions: true,
      prices: { full: 200, half: 120 },
      defaultPortion: 'full',
      prepTime: '15 min',
      badge: 'Mash Special / بھنی دال ماش',
      isExcludedFastFood: false,
    },
    {
      id: 'mix-sabzi',
      nameEn: 'Mix Sabzi',
      nameUr: 'مکس سبزی',
      categoryId: 'daal',
      menuGroup: 'extended',
      descriptionEn: 'Fresh seasonal vegetables wok-tossed with cumin seeds, fenugreek, and home-style ground spices.',
      descriptionUr: 'موسمی تازہ سبزیوں کا دیسی مصالحوں میں تیار شدہ لذیذ سالن۔',
      image: '/src/assets/images/dish_daal_makhni_1790249173685.jpg',
      hasPortions: true,
      prices: { full: 300, half: 180 },
      defaultPortion: 'full',
      prepTime: '15 min',
      badge: 'Fresh Farm / تازہ سبزی',
      isExcludedFastFood: false,
    },
    {
      id: 'chana-fry',
      nameEn: 'Chana Fry',
      nameUr: 'چنا فرائی',
      categoryId: 'daal',
      menuGroup: 'extended',
      descriptionEn: 'Chickpeas simmered in spiced gravy and finished with black pepper and ginger julienne.',
      descriptionUr: 'چٹپٹے مصالحے دار لاہوری چنا فرائی۔',
      image: '/src/assets/images/dish_daal_makhni_1790249173685.jpg',
      hasPortions: true,
      prices: { full: 300, half: 180 },
      defaultPortion: 'full',
      prepTime: '15 min',
      badge: 'Lahori Chana / چنا فرائی',
      isExcludedFastFood: false,
    },

    // --- Tandoor & Cold Drinks / Sides Matrix ---
    {
      id: 'tandoor-roghni-naan',
      nameEn: 'Roghni Naan',
      nameUr: 'روغنی نان',
      categoryId: 'tandoor',
      menuGroup: 'extended',
      descriptionEn: 'Clay-oven baked leavened bread brushed with warm desi ghee and toasted sesame seeds.',
      descriptionUr: 'دیسی گھی اور تلوں سے مزین تازہ تندوری روغنی نان۔',
      image: '/src/assets/images/dish_tandoor_naan_1790249200256.jpg',
      hasPortions: false,
      prices: { full: 70 },
      defaultPortion: 'full',
      prepTime: '5 min',
      isPopular: true,
      badge: 'Desi Ghee / روغنی نان',
      isExcludedFastFood: false,
    },
    {
      id: 'tandoor-roti',
      nameEn: 'Tandoori Roti',
      nameUr: 'تندوری روٹی',
      categoryId: 'tandoor',
      menuGroup: 'extended',
      descriptionEn: 'Fresh hot 100% whole wheat roti baked against red-hot clay tandoor walls.',
      descriptionUr: 'تازہ گرم روایتی تندوری گندم کی روٹی۔',
      image: '/src/assets/images/dish_tandoor_naan_1790249200256.jpg',
      hasPortions: false,
      prices: { full: 25 },
      defaultPortion: 'full',
      prepTime: '5 min',
      isPopular: false,
      badge: 'Whole Wheat / تندوری روٹی',
      isExcludedFastFood: false,
    },
    {
      id: 'tandoor-plain-naan',
      nameEn: 'Plain Naan',
      nameUr: 'سادہ نان',
      categoryId: 'tandoor',
      menuGroup: 'extended',
      descriptionEn: 'Fluffy, freshly baked plain leavened tandoor naan.',
      descriptionUr: 'تازہ گرم تندوری سادہ نان۔',
      image: '/src/assets/images/dish_tandoor_naan_1790249200256.jpg',
      hasPortions: false,
      prices: { full: 30 },
      defaultPortion: 'full',
      prepTime: '5 min',
      isExcludedFastFood: false,
    },
    {
      id: 'tandoor-kalonji-naan',
      nameEn: 'Kalonji Naan',
      nameUr: 'کلونجی نان',
      categoryId: 'tandoor',
      menuGroup: 'extended',
      descriptionEn: 'Tandoori naan topped with aromatic nigella seeds (kalonji).',
      descriptionUr: 'شفابخش اور خوشبودار کلونجی کے دانوں سے سجا نان۔',
      image: '/src/assets/images/dish_tandoor_naan_1790249200256.jpg',
      hasPortions: false,
      prices: { full: 40 },
      defaultPortion: 'full',
      prepTime: '5 min',
      badge: 'Kalonji / کلونجی',
      isExcludedFastFood: false,
    },
    {
      id: 'tandoor-garlic-naan',
      nameEn: 'Garlic Naan',
      nameUr: 'گارلک نان',
      categoryId: 'tandoor',
      menuGroup: 'extended',
      descriptionEn: 'Clay-oven naan infused with crushed fresh garlic cloves, coriander, and warm butter.',
      descriptionUr: 'تازہ لہسن، دھنیا اور مکھن سے مزین تندوری گارلک نان۔',
      image: '/src/assets/images/dish_tandoor_naan_1790249200256.jpg',
      hasPortions: false,
      prices: { full: 50 },
      defaultPortion: 'full',
      prepTime: '5 min',
      isPopular: true,
      badge: 'Fresh Garlic / گارلک نان',
      isExcludedFastFood: false,
    },
    {
      id: 'salad-fresh',
      nameEn: 'Fresh Salad',
      nameUr: 'تازہ سلاد',
      categoryId: 'tandoor',
      menuGroup: 'extended',
      descriptionEn: 'Crisp sliced cucumbers, red onions, tomatoes, radishes, and fresh lemon cuts.',
      descriptionUr: 'تازہ کٹے ہوئے کھیرے، پیاز، ٹماٹر اور لیموں کی پلیٹ۔',
      image: '/src/assets/images/dish_raita_salad_1790248480625.jpg',
      hasPortions: false,
      prices: { full: 100 },
      defaultPortion: 'full',
      prepTime: 'Instant / فوری',
      isExcludedFastFood: false,
    },
    {
      id: 'raita-zeera',
      nameEn: 'Zeera Raita',
      nameUr: 'زیرہ رائتہ',
      categoryId: 'tandoor',
      menuGroup: 'extended',
      descriptionEn: 'Whisked fresh yogurt infused with dry-roasted cumin seeds and rock salt.',
      descriptionUr: 'بھنے ہوئے زیرے اور کالا نمک ملا تازہ دہی کا رائتہ۔',
      image: '/src/assets/images/dish_raita_salad_1790248480625.jpg',
      hasPortions: false,
      prices: { full: 70 },
      defaultPortion: 'full',
      prepTime: 'Chilled / ٹھنڈا',
      isExcludedFastFood: false,
    },
    {
      id: 'raita-mint',
      nameEn: 'Mint Raita',
      nameUr: 'پودینہ رائتہ',
      categoryId: 'tandoor',
      menuGroup: 'extended',
      descriptionEn: 'Cool yogurt condiment blended with garden mint, coriander, and mild green chillies.',
      descriptionUr: 'تازہ پودینے اور دھنیے کی چٹنی ملا ٹھنڈا دہی کا رائتہ۔',
      image: '/src/assets/images/dish_raita_salad_1790248480625.jpg',
      hasPortions: false,
      prices: { full: 70 },
      defaultPortion: 'full',
      prepTime: 'Chilled / ٹھنڈا',
      isExcludedFastFood: false,
    },
  ],

  addOns: [
    {
      id: 'addon-regular-can',
      nameEn: 'Regular Can',
      nameUr: 'کین کولڈ ڈرنک (250 ملی)',
      category: 'drinks',
      price: 70,
      volumeOrSize: '250ml Can',
    },
    {
      id: 'addon-half-litre',
      nameEn: 'Half Litre',
      nameUr: 'آدھا لیٹر بوتل',
      category: 'drinks',
      price: 120,
      volumeOrSize: '500ml',
    },
    {
      id: 'addon-15-litre',
      nameEn: '1.5 Litre',
      nameUr: 'ڈیڑھ لیٹر بوتل',
      category: 'drinks',
      price: 220,
      volumeOrSize: '1.5L',
    },
    {
      id: 'addon-mineral-water',
      nameEn: 'Mineral Water',
      nameUr: 'منرل واٹر بوتل',
      category: 'drinks',
      price: 100,
      volumeOrSize: '500ml',
    },
    {
      id: 'addon-roghni-naan',
      nameEn: 'Roghni Naan',
      nameUr: 'روغنی نان',
      category: 'bread',
      price: 70,
      volumeOrSize: '1 Piece',
    },
    {
      id: 'addon-tandoori-roti',
      nameEn: 'Tandoori Roti',
      nameUr: 'تندوری روٹی',
      category: 'bread',
      price: 25,
      volumeOrSize: '1 Piece',
    },
    {
      id: 'addon-raita-salad',
      nameEn: 'Zeera Raita & Fresh Salad Plate',
      nameUr: 'زیرہ رائتہ اور تازہ سلاد',
      category: 'sides',
      price: 70,
      volumeOrSize: '1 Plate',
    },
  ],

  odooBlocks: [
    {
      id: 'odoo-woodfire-tradition',
      titleEn: 'Balochi Wood-Fired Roasting Mastery',
      titleUr: 'اصیل بلوچی کوئلہ سجی اور کچن کی روایت',
      subtitleEn: '4-Hour slow charcoal embers with mountain rock salts',
      subtitleUr: 'پہاڑی نمک اور روایتی مصالحوں کے ساتھ خالص انگاروں پر پکائی',
      contentEn: 'Every cut of meat at Dogar Sajji is prepared following authentic tribal heritage. Skewered whole over glowing acacia coals, our Sajji achieves unrivaled tenderness with crispy golden skin, retaining 100% natural juices without artificial tenderizers.',
      contentUr: 'ڈوگر سجی میں گوشت کو روایتی قبائلی طریقے سے تیار کیا جاتا ہے۔ کیکر کے خالص کوئلوں پر گھنٹوں دھیمی آنچ میں بھون کر بغیر کسی کیمیکل کے قدرتی ذائقہ اور خستگی حاصل کی جاتی ہے۔',
      shape: 'soft-curved',
      themeOverride: 'inherit',
      image: '/src/assets/images/hero_sajji_roast_banner_1790248382249.jpg',
      badgeEn: 'Time-Honored Craft',
      badgeUr: 'خالص روایتی طریقہ',
      callToActionTextEn: 'Order Hot Sajji via WhatsApp',
      callToActionTextUr: 'ہاٹ لائن واٹس ایپ آرڈر',
      callToActionLink: 'https://wa.me/923009346628?text=Salam%20Dogar%20Sajji%2C%20I%20want%20to%20order%20Balochi%20Sajji',
      isEnabled: true,
      displayOrder: 1,
      tagEn: 'Signature Craftsmanship / خاص مہارت',
      tagUr: 'اصلی ہیرٹیج',
    },
    {
      id: 'odoo-shinwari-wok',
      titleEn: 'Live Karahi & Pure Desi Ghee Hearth',
      titleUr: 'لائیو کڑاہی اور خالص دیسی گھی',
      subtitleEn: 'Fresh meat cooked on high flame in cast-iron woks',
      subtitleUr: 'صرف تازہ گوشت، ٹماٹر، ادرک اور دیسی گھی میں فوری پکائی',
      contentEn: 'Crafted on roaring gas hearths in pure desi ghee, our karahi lets the natural flavor of prime meat shine. No heavy commercial gravies or powders—just vine tomatoes, sea salt, ginger julienne, and whole green chillies.',
      contentUr: 'ہمارے کاریگر لوہے کی کڑاہی میں خالص دیسی گھی کے ساتھ تازہ گوشت اور ٹماٹروں سے کڑاہی تیار کرتے ہیں تاکہ آپ کو اصلی مہک اور روایتی ذائقہ ملے۔',
      shape: 'square',
      themeOverride: 'inherit',
      image: '/src/assets/images/dish_karahi_special_1790248428097.jpg',
      badgeEn: 'Pure Desi Ghee',
      badgeUr: 'خالص دیسی گھی',
      callToActionTextEn: 'Order Fresh Karahi',
      callToActionTextUr: 'دیسی کڑاہی آرڈر کریں',
      callToActionLink: 'https://wa.me/923009346628?text=Salam%2C%20I%20want%20to%20order%20Desi%20Karahi',
      isEnabled: true,
      displayOrder: 2,
      tagEn: 'Gastronomy Excellence / کڑاہی اسپیشل',
      tagUr: 'لائیو دسترخوان',
    },
    {
      id: 'odoo-family-banquet',
      titleEn: 'Family Hall & Grand Event Catering',
      titleUr: 'فیملی ڈائننگ ہال و تقریبات کیٹرنگ',
      subtitleEn: 'Air-conditioned VIP cabins and bulk outdoor live BBQ',
      subtitleUr: 'پُرسکون خاندانی ماحول، لائیو باربی کیو کیٹرنگ اور تقریبات کا انتظام',
      contentEn: 'Dogar Sajji & Restaurant offers comfortable family seating cabins alongside professional outdoor catering services for weddings, corporate feasts, and grand gatherings with live Sajji pits set up at your venue.',
      contentUr: 'ہماری وسیع اور باعزت فیملی ڈائننگ کے علاوہ شادی بیاہ اور نجی محافل کے لیے لائیو سجی اور کڑاہی کیٹرنگ کا شاندار بندوبست دستیاب ہے۔',
      shape: 'triangular-mask',
      themeOverride: 'inherit',
      image: '/src/assets/images/dish_combo_feast_1790249210676.jpg',
      badgeEn: 'VIP Family Dining',
      badgeUr: 'فیملی ہال و کیٹرنگ',
      callToActionTextEn: 'Book Catering via WhatsApp',
      callToActionTextUr: 'کیٹرنگ بکنگ (0300-9346628)',
      callToActionLink: 'https://wa.me/923009346628?text=Salam%2C%20I%20want%20to%20inquire%20about%20Dogar%20Sajji%20Catering%20or%20Family%20Hall',
      isEnabled: true,
      displayOrder: 3,
      tagEn: 'Hospitality & Events / کیٹرنگ سروس',
      tagUr: 'خصوصی تقریبات',
      pricingEn: 'From Rs. 850 / Person',
      pricingUr: 'پیکیج 850 روپے فی کس سے شروع',
      comboPackageDetails: 'Includes Live Sajji Roast, Desi Karahi, Fresh Tandoor Naan, Raita, Salad & Chilled Soft Drinks',
    },
  ],

  guidelines: [
    {
      id: 'g-fresh-meat',
      titleEn: 'Strict Daily Fresh Zabihah Standards',
      titleUr: 'روزانہ تازہ حلال ذبیحہ اور زیرو فریزڈ پالیسی',
      descriptionEn: 'Only certified same-day slaughtered whole chickens and young mountain goat meat are used. Zero frozen storage or chemical meat tenderizers.',
      descriptionUr: 'صرف اسی دن کا تازہ حلال ذبیحہ گوشت استعمال ہوتا ہے۔ کسی بھی قسم کا باسی یا فریزڈ گوشت سختی سے ممنوع ہے۔',
      iconName: 'Shield',
    },
    {
      id: 'g-wood-charcoal',
      titleEn: 'Authentic Acacia Wood Charcoal Roasting',
      titleUr: 'خالص کیکر کوئلے کا استعمال اور دھیمی آنچ',
      descriptionEn: 'Sajji is slowly roasted over natural acacia wood coals for a minimum of 35-40 minutes to guarantee golden crispy skin and moist interior.',
      descriptionUr: 'سجی کو اصلی کوئلوں کے انگاروں پر 35 سے 40 منٹ دھیمی آنچ میں سینکا جاتا ہے تاکہ گوشت اندر تک مکمل پک جائے۔',
      iconName: 'Flame',
    },
    {
      id: 'g-kitchen-hygiene',
      titleEn: 'Medical Grade Kitchen Sanitation & Hygiene',
      titleUr: 'طبی معیار کی صفائی اور جراثیم سے پاک کچن',
      descriptionEn: 'All stainless steel preparation surfaces, skewers, and woks undergo high-temperature steam sterilization before each service.',
      descriptionUr: 'تمام سیخیں، کڑاہیاں اور برتن ہر شفٹ میں کھولتے پانی اور سینیٹائزر سے مکمل صاف کیے جاتے ہیں۔',
      iconName: 'Sparkles',
    },
    {
      id: 'g-express-dispatch',
      titleEn: 'Thermal Bag Hot Food Dispatch (0300-9346628)',
      titleUr: 'تھرمل انسولیشن بیگز میں گرم کھانا فوری ترسیل',
      descriptionEn: 'Hotline delivery orders are sealed directly from the fire pit into insulated food bags to arrive piping hot at your doorstep.',
      descriptionUr: 'کوئلوں سے اترتے ہی کھانا خاص تھرمل بیگز میں پیک کر کے فوری طور پر آپ کے گھر روانہ کیا جاتا ہے۔',
      iconName: 'Clock',
    },
  ],

  galleryImages: [
    '/src/assets/images/dish_chicken_sajji_1790248406038.jpg',
    '/src/assets/images/dish_mutton_sajji_1790248417867.jpg',
    '/src/assets/images/dish_karahi_special_1790248428097.jpg',
    '/src/assets/images/dish_daal_makhni_1790249173685.jpg',
    '/src/assets/images/dish_beef_bihari_1790249187284.jpg',
    '/src/assets/images/dish_tandoor_naan_1790249200256.jpg',
  ],

  // OWNER PROFILE & PASSPORT SIZE FRAME
  ownerNameEn: 'Muhammad Dogar',
  ownerNameUr: 'محمد ڈوگر',
  ownerTitleEn: 'Founder, Owner & Master Pitmaster',
  ownerTitleUr: 'بانی و سرپرست اعلیٰ ڈوگر سجی',
  ownerMessageEn: 'Serving authentic Balochi wood-roasted Sajji and pure traditions with an uncompromising commitment to 100% daily fresh halal zabihah meat and hand-ground desi spices.',
  ownerMessageUr: 'ہماری اولین ترجیح خالص دیسی مسالوں اور روزانہ تازہ ذبیحہ کے ساتھ اصل بلوچی سجی کا روایتی ذائقہ آپ کے دسترخوان تک پہنچانا ہے۔',
  ownerPassportImage: '/src/assets/images/owner_muhammad_dogar_1790250637041.jpg',

  // 9 DYNAMIC RED-PIN LANDMARKS
  landmarks: LOCAL_LANDMARK_PINS,

  // DUAL-VIEW CARD ENGINE (MOBILE 1-ROW VS PC 2-GRID)
  catalogViewMode: 'mobile-default',

  // DEDICATED TYPOGRAPHY SEGMENTATION MODULE (THE TYPE SECTION ENGINE)
  activeTypographyLayout: 'clean-minimalist-sans',
  activeTextColorPalette: 'charcoal-gold',

  // 5 DYNAMIC RAINBOW BUTTON ACCENT TEMPLATES + DEFAULT
  activeButtonTheme: 'default-emerald-rose',
};
