import { 
  BlockStyleSchemeConfig, 
  LightingModeConfig, 
  ThemeId, 
  ThemeStyleConfig,
  TypographyLayoutConfig,
  TextColorPaletteConfig,
  ButtonThemeConfig
} from '../types';

export const THEMES_REGISTRY: Record<ThemeId, ThemeStyleConfig> = {
  // =========================================================================
  // LAYER A: 6 MASTER GLOBAL PALETTES
  // =========================================================================

  // 1. Pure Clean White Canvas (Default)
  'clean-white': {
    id: 'clean-white',
    nameEn: 'Pure Clean White Canvas',
    nameUr: 'خالص سفید کینوس (ڈیفالٹ)',
    type: 'global',
    badge: 'Default Canvas #FFFFFF',
    bgCanvas: '#FFFFFF',
    bgSurface: '#F8FAFC',
    bgSurfaceHover: '#F1F5F9',
    bgCard: '#FFFFFF',
    textPrimary: '#0F172A',
    textSecondary: '#475569',
    textMuted: '#94A3B8',
    accent: '#EA580C', // warm rich roast ember
    accentHover: '#C2410C',
    accentText: '#FFFFFF',
    borderSubtle: 'rgba(15, 23, 42, 0.08)',
    borderStrong: 'rgba(15, 23, 42, 0.16)',
    pillActiveBg: '#0F172A',
    pillActiveText: '#FFFFFF',
    specialClass: 'theme-clean-white',
  },

  // 2. Charcoal Dark Gold
  'charcoal-gold': {
    id: 'charcoal-gold',
    nameEn: 'Charcoal Dark Gold',
    nameUr: 'چارکول ڈارک گولڈ',
    type: 'global',
    badge: 'Luxury Dark · Amber Gold',
    bgCanvas: '#0F1115',
    bgSurface: '#181B22',
    bgSurfaceHover: '#222631',
    bgCard: '#181B22',
    textPrimary: '#F8FAFC',
    textSecondary: '#CBD5E1',
    textMuted: '#64748B',
    accent: '#D97706', // warm amber gold
    accentHover: '#B45309',
    accentText: '#000000',
    borderSubtle: 'rgba(217, 119, 6, 0.15)',
    borderStrong: 'rgba(217, 119, 6, 0.35)',
    pillActiveBg: '#D97706',
    pillActiveText: '#000000',
    specialClass: 'theme-charcoal-gold',
  },

  // 3. Smoky Yellow & Warm Rose
  'smoky-rose': {
    id: 'smoky-rose',
    nameEn: 'Smoky Yellow & Warm Rose',
    nameUr: 'سموکی یلو اور وارم روز',
    type: 'global',
    badge: 'Artisanal Sunset Dusk',
    bgCanvas: '#140E10',
    bgSurface: '#201418',
    bgSurfaceHover: '#2C1B22',
    bgCard: '#1C1216',
    textPrimary: '#FFF1F4',
    textSecondary: '#F3B4C4',
    textMuted: '#A36879',
    accent: '#EAB308', // brilliant sunny gold
    accentHover: '#CA8A04',
    accentText: '#140E10',
    borderSubtle: 'rgba(234, 179, 8, 0.18)',
    borderStrong: 'rgba(244, 63, 94, 0.38)',
    pillActiveBg: '#EAB308',
    pillActiveText: '#140E10',
    specialClass: 'theme-smoky-rose',
  },

  // 4. Midnight Minimalist Black
  'midnight-black': {
    id: 'midnight-black',
    nameEn: 'Midnight Minimalist Black',
    nameUr: 'مڈ نائٹ منیملسٹ بلیک',
    type: 'global',
    badge: 'Ultra Deep Minimalist',
    bgCanvas: '#09090B',
    bgSurface: '#121215',
    bgSurfaceHover: '#18181D',
    bgCard: '#141418',
    textPrimary: '#FAFAFA',
    textSecondary: '#A1A1AA',
    textMuted: '#71717A',
    accent: '#F43F5E', // sharp rose ember
    accentHover: '#E11D48',
    accentText: '#FFFFFF',
    borderSubtle: 'rgba(255, 255, 255, 0.08)',
    borderStrong: 'rgba(255, 255, 255, 0.18)',
    pillActiveBg: '#27272A',
    pillActiveText: '#FAFAFA',
    specialClass: 'theme-midnight-black',
  },

  // 5. Deep Emerald Luxury
  'emerald-luxury': {
    id: 'emerald-luxury',
    nameEn: 'Deep Emerald Luxury',
    nameUr: 'خالص زمردی لگژری',
    type: 'global',
    badge: 'Imperial Jade Royal',
    bgCanvas: '#041811',
    bgSurface: '#08281C',
    bgSurfaceHover: '#0D3627',
    bgCard: '#072419',
    textPrimary: '#F2FDF6',
    textSecondary: '#A7F3D0',
    textMuted: '#34D399',
    accent: '#10B981', // emerald glow
    accentHover: '#059669',
    accentText: '#041811',
    borderSubtle: 'rgba(16, 185, 129, 0.18)',
    borderStrong: 'rgba(16, 185, 129, 0.38)',
    pillActiveBg: '#10B981',
    pillActiveText: '#041811',
    specialClass: 'theme-emerald-luxury',
  },

  // 6. Crimson Red & Cream
  'crimson-cream': {
    id: 'crimson-cream',
    nameEn: 'Crimson Red & Cream',
    nameUr: 'سرخ کرمسن اور ملائی',
    type: 'global',
    badge: 'Heritage Feast · Mughal Spice',
    bgCanvas: '#FDF8F5',
    bgSurface: '#F9ECE5',
    bgSurfaceHover: '#F4DDD2',
    bgCard: '#FFFFFF',
    textPrimary: '#2D0A0E',
    textSecondary: '#6E4247',
    textMuted: '#A0767C',
    accent: '#DC2626', // rich royal crimson
    accentHover: '#B91C1C',
    accentText: '#FFFFFF',
    borderSubtle: 'rgba(220, 38, 38, 0.12)',
    borderStrong: 'rgba(220, 38, 38, 0.28)',
    pillActiveBg: '#DC2626',
    pillActiveText: '#FFFFFF',
    specialClass: 'theme-crimson-cream',
  },

  // Legacy mappings for backwards compatibility
  'terracotta-bistro': {
    id: 'terracotta-bistro',
    nameEn: 'Warm Terracotta Bistro',
    nameUr: 'گرم ٹیراکوٹا بسٹرو',
    type: 'global',
    badge: 'Earthy Clay',
    bgCanvas: '#FDFBF7',
    bgSurface: '#F7F2EA',
    bgSurfaceHover: '#EFE7DC',
    bgCard: '#FFFFFF',
    textPrimary: '#291811',
    textSecondary: '#6E5D53',
    textMuted: '#A08D83',
    accent: '#C2410C',
    accentHover: '#9A3412',
    accentText: '#FFFFFF',
    borderSubtle: 'rgba(67, 33, 18, 0.10)',
    borderStrong: 'rgba(67, 33, 18, 0.22)',
    pillActiveBg: '#C2410C',
    pillActiveText: '#FFFFFF',
  },
  'midnight-sapphire': {
    id: 'midnight-sapphire',
    nameEn: 'Midnight Sapphire',
    nameUr: 'مڈ نائٹ سیفائر',
    type: 'global',
    badge: 'Deep Oceanic',
    bgCanvas: '#0A0F1D',
    bgSurface: '#111A30',
    bgSurfaceHover: '#182444',
    bgCard: '#111A30',
    textPrimary: '#F0F6FC',
    textSecondary: '#94A3B8',
    textMuted: '#475569',
    accent: '#0284C7',
    accentHover: '#0369A1',
    accentText: '#FFFFFF',
    borderSubtle: 'rgba(2, 132, 199, 0.18)',
    borderStrong: 'rgba(2, 132, 199, 0.35)',
    pillActiveBg: '#0284C7',
    pillActiveText: '#FFFFFF',
  },
  'vintage-olive': {
    id: 'vintage-olive',
    nameEn: 'Vintage Olive & Brass',
    nameUr: 'ونٹیج زیتونی و پیتل',
    type: 'global',
    badge: 'Artisanal Heritage',
    bgCanvas: '#141815',
    bgSurface: '#1D2420',
    bgSurfaceHover: '#26302A',
    bgCard: '#1D2420',
    textPrimary: '#EDEFEA',
    textSecondary: '#A7B2A8',
    textMuted: '#687369',
    accent: '#CA8A04',
    accentHover: '#A16207',
    accentText: '#141815',
    borderSubtle: 'rgba(202, 138, 4, 0.18)',
    borderStrong: 'rgba(202, 138, 4, 0.35)',
    pillActiveBg: '#CA8A04',
    pillActiveText: '#141815',
  },
  'sand-linen': {
    id: 'sand-linen',
    nameEn: 'Minimalist Sand & Linen',
    nameUr: 'سادہ ریت و کتانی انداز',
    type: 'global',
    badge: 'Nordic Organic',
    bgCanvas: '#F5F2EB',
    bgSurface: '#EBE6DC',
    bgSurfaceHover: '#DFD9CD',
    bgCard: '#FFFFFF',
    textPrimary: '#262422',
    textSecondary: '#57524C',
    textMuted: '#948D84',
    accent: '#78350F',
    accentHover: '#92400E',
    accentText: '#FFFFFF',
    borderSubtle: 'rgba(38, 36, 34, 0.08)',
    borderStrong: 'rgba(38, 36, 34, 0.18)',
    pillActiveBg: '#262422',
    pillActiveText: '#FFFFFF',
  },

  // 3 ARTISTIC BESPOKE PRESETS
  'cherry-pin': {
    id: 'cherry-pin',
    nameEn: 'Cherry Pin',
    nameUr: 'چیری پن (لگژری روز)',
    type: 'bespoke',
    badge: 'Bespoke Preset · Rose & Stark Luxury',
    bgCanvas: '#0F090B',
    bgSurface: '#1F1116',
    bgSurfaceHover: '#2C1720',
    bgCard: '#1A0E13',
    textPrimary: '#FFF1F4',
    textSecondary: '#F3B4C4',
    textMuted: '#965E6F',
    accent: '#E11D48',
    accentHover: '#BE123C',
    accentText: '#FFFFFF',
    borderSubtle: 'rgba(225, 29, 72, 0.22)',
    borderStrong: 'rgba(244, 63, 94, 0.45)',
    pillActiveBg: 'linear-gradient(135deg, #BE123C 0%, #E11D48 100%)',
    pillActiveText: '#FFFFFF',
    gradientAccent: 'from-rose-500/20 via-pink-900/10 to-transparent',
    specialClass: 'theme-cherry-pin',
  },
  'smok': {
    id: 'smok',
    nameEn: 'Smok',
    nameUr: 'سموک (دھندلا چارکول)',
    type: 'bespoke',
    badge: 'Bespoke Preset · Moody Translucent Bistro',
    bgCanvas: '#0A0A0C',
    bgSurface: 'rgba(24, 24, 28, 0.72)',
    bgSurfaceHover: 'rgba(36, 36, 44, 0.85)',
    bgCard: 'rgba(20, 20, 24, 0.65)',
    textPrimary: '#F4F4F6',
    textSecondary: '#A1A1AA',
    textMuted: '#52525B',
    accent: '#71717A',
    accentHover: '#A1A1AA',
    accentText: '#FFFFFF',
    borderSubtle: 'rgba(255, 255, 255, 0.08)',
    borderStrong: 'rgba(255, 255, 255, 0.18)',
    pillActiveBg: 'rgba(255, 255, 255, 0.15)',
    pillActiveText: '#FFFFFF',
    gradientAccent: 'from-zinc-800/40 via-neutral-900/60 to-black',
    specialClass: 'theme-smok backdrop-blur-xl',
  },
  'green-sunlight': {
    id: 'green-sunlight',
    nameEn: 'Green Land & Yellow Sunlight',
    nameUr: 'گرین لینڈ اور روشن زرد سورج',
    type: 'bespoke',
    badge: 'Bespoke Preset · Emerald Organic & Yellow Glow',
    bgCanvas: '#041811',
    bgSurface: '#08281C',
    bgSurfaceHover: '#0D3627',
    bgCard: '#072419',
    textPrimary: '#F2FDF6',
    textSecondary: '#A7F3D0',
    textMuted: '#34D399',
    accent: '#FACC15',
    accentHover: '#EAB308',
    accentText: '#041811',
    borderSubtle: 'rgba(250, 204, 21, 0.22)',
    borderStrong: 'rgba(250, 204, 21, 0.45)',
    pillActiveBg: '#FACC15',
    pillActiveText: '#041811',
    gradientAccent: 'from-emerald-950 via-teal-900/40 to-yellow-950/20',
    specialClass: 'theme-green-sunlight',
  },

  // =========================================================================
  // 6 MULTI-COLOR RAINBOW SCHEMES (HARDWARE-ACCELERATED VIBRANT SPECTRUM)
  // =========================================================================
  'rainbow-aurora-spectrum': {
    id: 'rainbow-aurora-spectrum',
    nameEn: 'Aurora Spectrum Hologram',
    nameUr: 'شفق قطبی رینبو سپیکٹرم',
    type: 'global',
    badge: 'Rainbow Scheme 1 · Multi-Hue Spectrum',
    bgCanvas: '#0A0614',
    bgSurface: 'rgba(25, 15, 45, 0.85)',
    bgSurfaceHover: 'rgba(38, 22, 68, 0.95)',
    bgCard: '#130B24',
    textPrimary: '#FFFFFF',
    textSecondary: '#E9D5FF',
    textMuted: '#A855F7',
    accent: '#EC4899',
    accentHover: '#DB2777',
    accentText: '#FFFFFF',
    borderSubtle: 'rgba(236, 72, 153, 0.25)',
    borderStrong: 'rgba(168, 85, 247, 0.45)',
    pillActiveBg: 'linear-gradient(135deg, #FF007A 0%, #7928CA 50%, #00DFD8 100%)',
    pillActiveText: '#FFFFFF',
    specialClass: 'theme-rainbow-aurora-spectrum bg-linear-to-br from-purple-950/70 via-slate-950 to-pink-950/50',
  },
  'rainbow-sunset-prism': {
    id: 'rainbow-sunset-prism',
    nameEn: 'Sunset Prism Rainbow',
    nameUr: 'غروب آفتاب پرزم رینبو',
    type: 'global',
    badge: 'Rainbow Scheme 2 · Prismatic Sunset',
    bgCanvas: '#12070A',
    bgSurface: 'rgba(35, 12, 20, 0.85)',
    bgSurfaceHover: 'rgba(50, 18, 30, 0.95)',
    bgCard: '#1D0A12',
    textPrimary: '#FFF5F5',
    textSecondary: '#FECDD3',
    textMuted: '#FB7185',
    accent: '#F97316',
    accentHover: '#EA580C',
    accentText: '#FFFFFF',
    borderSubtle: 'rgba(249, 115, 22, 0.25)',
    borderStrong: 'rgba(244, 63, 94, 0.45)',
    pillActiveBg: 'linear-gradient(135deg, #F43F5E 0%, #FB923C 50%, #A855F7 100%)',
    pillActiveText: '#FFFFFF',
    specialClass: 'theme-rainbow-sunset-prism bg-linear-to-br from-rose-950/70 via-zinc-950 to-amber-950/50',
  },
  'rainbow-neon-iridescent': {
    id: 'rainbow-neon-iridescent',
    nameEn: 'Neon Iridescent Flow',
    nameUr: 'نیون قوس قزح چمکدار لہر',
    type: 'global',
    badge: 'Rainbow Scheme 3 · Cyber Iridescent',
    bgCanvas: '#050B14',
    bgSurface: 'rgba(10, 24, 45, 0.85)',
    bgSurfaceHover: 'rgba(15, 36, 68, 0.95)',
    bgCard: '#08162A',
    textPrimary: '#F0FDFA',
    textSecondary: '#99F6E4',
    textMuted: '#2DD4BF',
    accent: '#06B6D4',
    accentHover: '#0891B2',
    accentText: '#000000',
    borderSubtle: 'rgba(6, 182, 212, 0.25)',
    borderStrong: 'rgba(59, 130, 246, 0.45)',
    pillActiveBg: 'linear-gradient(135deg, #00F5A0 0%, #00D9F5 50%, #7928CA 100%)',
    pillActiveText: '#000000',
    specialClass: 'theme-rainbow-neon-iridescent bg-linear-to-br from-cyan-950/70 via-slate-950 to-indigo-950/50',
  },
  'rainbow-cosmic-chroma': {
    id: 'rainbow-cosmic-chroma',
    nameEn: 'Cosmic Chroma Gradient',
    nameUr: 'کائناتی کروما گریڈینٹ',
    type: 'global',
    badge: 'Rainbow Scheme 4 · Multi-Spectral Wash',
    bgCanvas: '#0B0819',
    bgSurface: 'rgba(22, 16, 48, 0.85)',
    bgSurfaceHover: 'rgba(34, 25, 72, 0.95)',
    bgCard: '#130E2A',
    textPrimary: '#FAF5FF',
    textSecondary: '#E9D5FF',
    textMuted: '#C084FC',
    accent: '#8B5CF6',
    accentHover: '#7C3AED',
    accentText: '#FFFFFF',
    borderSubtle: 'rgba(139, 92, 246, 0.25)',
    borderStrong: 'rgba(217, 70, 239, 0.45)',
    pillActiveBg: 'linear-gradient(135deg, #8B5CF6 0%, #D946EF 50%, #06B6D4 100%)',
    pillActiveText: '#FFFFFF',
    specialClass: 'theme-rainbow-cosmic-chroma bg-linear-to-br from-indigo-950/70 via-neutral-950 to-fuchsia-950/50',
  },
  'rainbow-tropical-opal': {
    id: 'rainbow-tropical-opal',
    nameEn: 'Tropical Opal Radiance',
    nameUr: 'ٹراپیکل اوپل رینبو ریڈینس',
    type: 'global',
    badge: 'Rainbow Scheme 5 · Opal Iridescence',
    bgCanvas: '#041412',
    bgSurface: 'rgba(8, 38, 34, 0.85)',
    bgSurfaceHover: 'rgba(12, 52, 47, 0.95)',
    bgCard: '#072622',
    textPrimary: '#ECFDF5',
    textSecondary: '#A7F3D0',
    textMuted: '#34D399',
    accent: '#10B981',
    accentHover: '#059669',
    accentText: '#041412',
    borderSubtle: 'rgba(16, 185, 129, 0.25)',
    borderStrong: 'rgba(234, 179, 8, 0.45)',
    pillActiveBg: 'linear-gradient(135deg, #10B981 0%, #F59E0B 50%, #EC4899 100%)',
    pillActiveText: '#041412',
    specialClass: 'theme-rainbow-tropical-opal bg-linear-to-br from-emerald-950/70 via-slate-950 to-teal-950/50',
  },
  'rainbow-cyber-wave': {
    id: 'rainbow-cyber-wave',
    nameEn: 'Cyberpunk Spectrum Wave',
    nameUr: 'سائبر پنک سپیکٹرم ویو',
    type: 'global',
    badge: 'Rainbow Scheme 6 · High-Voltage Ripple',
    bgCanvas: '#050508',
    bgSurface: 'rgba(18, 18, 28, 0.85)',
    bgSurfaceHover: 'rgba(28, 28, 42, 0.95)',
    bgCard: '#0F0F18',
    textPrimary: '#FFFFFF',
    textSecondary: '#CBD5E1',
    textMuted: '#64748B',
    accent: '#F43F5E',
    accentHover: '#E11D48',
    accentText: '#FFFFFF',
    borderSubtle: 'rgba(244, 63, 94, 0.3)',
    borderStrong: 'rgba(56, 189, 248, 0.5)',
    pillActiveBg: 'linear-gradient(135deg, #FF007A 0%, #00DFD8 50%, #F59E0B 100%)',
    pillActiveText: '#FFFFFF',
    specialClass: 'theme-rainbow-cyber-wave bg-linear-to-br from-slate-950 via-zinc-950 to-neutral-950',
  },

  // =========================================================================
  // 6 BALANCED MULTI-TONE MATRICES (3 TO 4 COMPLEMENTARY SOLID RICH COLORS)
  // =========================================================================
  'multitone-emerald-gold': {
    id: 'multitone-emerald-gold',
    nameEn: 'Royal Velvet & Emerald Gold',
    nameUr: 'شاہی مخمل و زمردی گولڈ',
    type: 'global',
    badge: 'Multi-Tone 1 · 4 Solid Tones: Emerald, Plum, Gold, Midnight',
    bgCanvas: '#061A14',
    bgSurface: '#0E2820',
    bgSurfaceHover: '#16382D',
    bgCard: '#102E24',
    textPrimary: '#FDFBF7',
    textSecondary: '#D1FAE5',
    textMuted: '#6EE7B7',
    accent: '#F59E0B', // imperial gold
    accentHover: '#D97706',
    accentText: '#061A14',
    borderSubtle: 'rgba(245, 158, 11, 0.2)',
    borderStrong: 'rgba(16, 185, 129, 0.4)',
    pillActiveBg: '#F59E0B',
    pillActiveText: '#061A14',
    specialClass: 'theme-multitone-emerald-gold',
  },
  'multitone-terracotta-charcoal': {
    id: 'multitone-terracotta-charcoal',
    nameEn: 'Saffron Terracotta & Charcoal',
    nameUr: 'زعفرانی ٹیراکوٹا و چارکول',
    type: 'global',
    badge: 'Multi-Tone 2 · 4 Solid Tones: Saffron, Terracotta, Charcoal, Cream',
    bgCanvas: '#141210',
    bgSurface: '#1F1B18',
    bgSurfaceHover: '#2B2521',
    bgCard: '#1C1814',
    textPrimary: '#FFFBEB',
    textSecondary: '#FDE68A',
    textMuted: '#D97706',
    accent: '#EA580C', // rich terracotta
    accentHover: '#C2410C',
    accentText: '#FFFFFF',
    borderSubtle: 'rgba(234, 88, 12, 0.2)',
    borderStrong: 'rgba(217, 119, 6, 0.4)',
    pillActiveBg: '#EA580C',
    pillActiveText: '#FFFFFF',
    specialClass: 'theme-multitone-terracotta-charcoal',
  },
  'multitone-sapphire-brass': {
    id: 'multitone-sapphire-brass',
    nameEn: 'Imperial Sapphire & Crimson Brass',
    nameUr: 'شاہی نیلم و کرمسن پیتل',
    type: 'global',
    badge: 'Multi-Tone 3 · 4 Solid Tones: Sapphire Navy, Crimson, Antique Brass, Pearl',
    bgCanvas: '#0A111E',
    bgSurface: '#101B2E',
    bgSurfaceHover: '#182844',
    bgCard: '#122038',
    textPrimary: '#F8FAFC',
    textSecondary: '#CBD5E1',
    textMuted: '#94A3B8',
    accent: '#DC2626', // rich crimson
    accentHover: '#B91C1C',
    accentText: '#FFFFFF',
    borderSubtle: 'rgba(220, 38, 38, 0.2)',
    borderStrong: 'rgba(217, 119, 6, 0.4)',
    pillActiveBg: '#DC2626',
    pillActiveText: '#FFFFFF',
    specialClass: 'theme-multitone-sapphire-brass',
  },
  'multitone-desert-sunset': {
    id: 'multitone-desert-sunset',
    nameEn: 'Balochi Desert Sunset Quad',
    nameUr: 'بلوچی صحرائی غروب آفتاب',
    type: 'global',
    badge: 'Multi-Tone 4 · 4 Solid Tones: Warm Ochre, Dusty Rose, Umber, Sand',
    bgCanvas: '#18100C',
    bgSurface: '#261812',
    bgSurfaceHover: '#342219',
    bgCard: '#221510',
    textPrimary: '#FFF7ED',
    textSecondary: '#FED7AA',
    textMuted: '#FB923C',
    accent: '#E11D48', // dusty rose ember
    accentHover: '#BE123C',
    accentText: '#FFFFFF',
    borderSubtle: 'rgba(225, 29, 72, 0.2)',
    borderStrong: 'rgba(249, 115, 22, 0.4)',
    pillActiveBg: '#E11D48',
    pillActiveText: '#FFFFFF',
    specialClass: 'theme-multitone-desert-sunset',
  },
  'multitone-copper-teal': {
    id: 'multitone-copper-teal',
    nameEn: 'Majestic Copper & Forest Teal',
    nameUr: 'تانبا کاپر اور جنگلی ٹیل',
    type: 'global',
    badge: 'Multi-Tone 5 · 4 Solid Tones: Burnished Copper, Forest Teal, Slate, Ivory',
    bgCanvas: '#081717',
    bgSurface: '#0E2424',
    bgSurfaceHover: '#143333',
    bgCard: '#102A2A',
    textPrimary: '#F0FDFA',
    textSecondary: '#99F6E4',
    textMuted: '#2DD4BF',
    accent: '#C2410C', // burnished copper
    accentHover: '#9A3412',
    accentText: '#FFFFFF',
    borderSubtle: 'rgba(194, 65, 12, 0.25)',
    borderStrong: 'rgba(20, 184, 166, 0.4)',
    pillActiveBg: '#C2410C',
    pillActiveText: '#FFFFFF',
    specialClass: 'theme-multitone-copper-teal',
  },
  'multitone-castiron-paprika': {
    id: 'multitone-castiron-paprika',
    nameEn: 'Artisan Cast Iron & Smoked Paprika',
    nameUr: 'ڈھلوان لوہا اور سموکڈ پیپریکا',
    type: 'global',
    badge: 'Multi-Tone 6 · 4 Solid Tones: Charred Iron, Smoked Paprika, Olive Leaf, Linen',
    bgCanvas: '#111113',
    bgSurface: '#19191D',
    bgSurfaceHover: '#232328',
    bgCard: '#1C1C20',
    textPrimary: '#FBF8F3',
    textSecondary: '#E4E4E7',
    textMuted: '#A1A1AA',
    accent: '#EF4444', // smoked paprika red
    accentHover: '#DC2626',
    accentText: '#FFFFFF',
    borderSubtle: 'rgba(239, 68, 68, 0.2)',
    borderStrong: 'rgba(245, 158, 11, 0.4)',
    pillActiveBg: '#EF4444',
    pillActiveText: '#FFFFFF',
    specialClass: 'theme-multitone-castiron-paprika',
  },
};

// =========================================================================
// LAYER B: 6 BLOCK-LEVEL STYLE SCHEMES (ISOLATED ODOO ROWS & GRIDS)
// =========================================================================
export const BLOCK_STYLE_SCHEMES: BlockStyleSchemeConfig[] = [
  {
    id: 'block-elevated-card',
    nameEn: 'Elevated Card',
    nameUr: 'ایلیویٹڈ کارڈ ود شیڈو',
    description: 'Crisp container with elevated drop-shadow and clean border accents.',
    cardClass: 'shadow-xl border border-white/10 hover:shadow-2xl transition-shadow',
    badge: 'Layer B · Scheme 1',
  },
  {
    id: 'block-glassmorphism',
    nameEn: 'Frosted Glassmorphism',
    nameUr: 'فراسٹیڈ گلاسمورفزم',
    description: 'Ultra-modern translucent backdrop blur with subtle rim highlights.',
    cardClass: 'backdrop-blur-xl bg-white/5 border border-white/15 shadow-2xl',
    badge: 'Layer B · Scheme 2',
  },
  {
    id: 'block-accent-border',
    nameEn: 'High-Contrast Accent Border',
    nameUr: 'ہائی کنٹراسٹ بارڈر',
    description: 'Distinctive 2px accent framing with warm amber edge glow.',
    cardClass: 'border-2 border-amber-500/80 shadow-[0_0_20px_rgba(245,158,11,0.15)]',
    badge: 'Layer B · Scheme 3',
  },
  {
    id: 'block-dark-inset',
    nameEn: 'Deep Dark Inset Chamber',
    nameUr: 'ڈیپ ڈارک چیمبر',
    description: 'Rich dark sunken surface with inner shadow for high contrast.',
    cardClass: 'bg-black/60 shadow-inner border border-white/10',
    badge: 'Layer B · Scheme 4',
  },
  {
    id: 'block-warm-parchment',
    nameEn: 'Warm Desi Parchment',
    nameUr: 'روایتی دیسی پرچمنٹ',
    description: 'Earthy warm tone reminiscent of traditional woodfire kitchens.',
    cardClass: 'bg-amber-950/20 border border-amber-600/30 shadow-md',
    badge: 'Layer B · Scheme 5',
  },
  {
    id: 'block-split-contrast',
    nameEn: 'Split Two-Tone Contrast',
    nameUr: 'ٹو ٹون کنٹراسٹ',
    description: 'Subtle gradient wash with split border detailing.',
    cardClass: 'bg-linear-to-br from-slate-900/80 to-amber-950/30 border border-amber-500/30 shadow-lg',
    badge: 'Layer B · Scheme 6',
  },
];

// =========================================================================
// LAYER C: 6 CUSTOM LIGHTING MODES (DYNAMIC AMBIENT FILTERS)
// =========================================================================
export const LIGHTING_MODES: LightingModeConfig[] = [
  {
    id: 'neon-glow',
    nameEn: 'Neon Glow Borders',
    nameUr: 'نیون گلو بارڈرز',
    description: 'Luminous neon edge projection for high-voltage nighttime presence.',
    glowClass: 'shadow-[0_0_30px_rgba(234,88,12,0.45)] ring-1 ring-amber-500/70',
    badge: 'Layer C · Mode 1',
  },
  {
    id: 'night-backlight',
    nameEn: 'Night-Mode Backlighting',
    nameUr: 'نائٹ موڈ بیک لائٹنگ',
    description: 'Deep halo ambient glow emanating softly behind foreground cards.',
    glowClass: 'shadow-[0_12px_45px_rgba(0,0,0,0.85)] ring-1 ring-white/15',
    badge: 'Layer C · Mode 2',
  },
  {
    id: 'golden-radiance',
    nameEn: 'Soft Golden Radiance',
    nameUr: 'سنہری روشنی و تجلی',
    description: 'Warm regal golden diffusion honoring traditional charcoal sajji flame.',
    glowClass: 'shadow-[0_0_35px_rgba(217,119,6,0.35)] ring-1 ring-amber-400/50',
    badge: 'Layer C · Mode 3',
  },
  {
    id: 'emerald-shimmer',
    nameEn: 'Emerald Shimmer',
    nameUr: 'زمردی چمک و جھلک',
    description: 'Cool jade aura signifying freshness, purity, and 100% halal assurance.',
    glowClass: 'shadow-[0_0_32px_rgba(16,185,129,0.35)] ring-1 ring-emerald-500/50',
    badge: 'Layer C · Mode 4',
  },
  {
    id: 'pulse-borders',
    nameEn: 'Pulse-Borders',
    nameUr: 'پلسنگ و متحرک بارڈرز',
    description: 'Subtle rhythmic breath effect highlighting transactional CTA zones.',
    glowClass: 'animate-pulse shadow-lg ring-2 ring-amber-500/80',
    badge: 'Layer C · Mode 5',
  },
  {
    id: 'minimalist-flat',
    nameEn: 'Static Minimalist Flat',
    nameUr: 'اسٹیٹک فلیٹ سادہ انداز',
    description: 'Zero ambient filter distraction with pure geometric structure.',
    glowClass: 'shadow-none ring-0',
    badge: 'Layer C · Mode 6',
  },
];

export const PRIMARY_6_GLOBAL_THEMES: ThemeStyleConfig[] = [
  THEMES_REGISTRY['clean-white'],
  THEMES_REGISTRY['charcoal-gold'],
  THEMES_REGISTRY['smok'],
  THEMES_REGISTRY['green-sunlight'],
  THEMES_REGISTRY['midnight-black'],
  THEMES_REGISTRY['emerald-luxury'],
];

export const BESPOKE_THEMES: ThemeStyleConfig[] = [
  THEMES_REGISTRY['smoky-rose'],
  THEMES_REGISTRY['crimson-cream'],
  THEMES_REGISTRY['cherry-pin'],
];

// 6 MULTI-COLOR RAINBOW SCHEMES
export const RAINBOW_THEMES: ThemeStyleConfig[] = [
  THEMES_REGISTRY['rainbow-aurora-spectrum'],
  THEMES_REGISTRY['rainbow-sunset-prism'],
  THEMES_REGISTRY['rainbow-neon-iridescent'],
  THEMES_REGISTRY['rainbow-cosmic-chroma'],
  THEMES_REGISTRY['rainbow-tropical-opal'],
  THEMES_REGISTRY['rainbow-cyber-wave'],
];

// 6 BALANCED MULTI-TONE MATRICES
export const MULTITONE_THEMES: ThemeStyleConfig[] = [
  THEMES_REGISTRY['multitone-emerald-gold'],
  THEMES_REGISTRY['multitone-terracotta-charcoal'],
  THEMES_REGISTRY['multitone-sapphire-brass'],
  THEMES_REGISTRY['multitone-desert-sunset'],
  THEMES_REGISTRY['multitone-copper-teal'],
  THEMES_REGISTRY['multitone-castiron-paprika'],
];

export const GLOBAL_THEMES = PRIMARY_6_GLOBAL_THEMES;

// =========================================================================
// 6 TYPOGRAPHY THEMATIC LAYOUTS (THE TYPE SECTION ENGINE)
// =========================================================================
export const TYPOGRAPHY_LAYOUTS: TypographyLayoutConfig[] = [
  {
    id: 'modern-nastaliq-serif',
    nameEn: 'Modern Nastaliq Serif',
    nameUr: 'ماڈرن نستعلیق سیرف',
    description: 'High-contrast editorial serif paired with authentic Nastaliq Urdu rhythm and medium Roman subtext.',
    badge: 'Layout 1 · Editorial Serif Blend',
    fontFamilyClass: 'font-serif',
    headingStyle: 'font-serif font-black tracking-tight',
    urduStyle: 'font-urdu font-black tracking-normal leading-normal',
    subtextStyle: 'font-sans font-medium tracking-normal',
    priceStyle: 'font-serif font-black tabular-nums tracking-tight',
  },
  {
    id: 'bold-heritage-kufic',
    nameEn: 'Bold Heritage Kufic Blend',
    nameUr: 'بولڈ ہیرٹیج کوفی بلینڈ',
    description: 'Heavyweight geometric display headings, bold Kufic-inspired Urdu weights, tight authoritative tracking.',
    badge: 'Layout 2 · Heavy Heritage Kufic',
    fontFamilyClass: 'font-display',
    headingStyle: 'font-display font-black tracking-tighter uppercase',
    urduStyle: 'font-urdu font-black tracking-tight leading-relaxed',
    subtextStyle: 'font-sans font-bold tracking-wide',
    priceStyle: 'font-mono font-black tabular-nums',
  },
  {
    id: 'clean-minimalist-sans',
    nameEn: 'Clean Minimalist Sans',
    nameUr: 'کلین منیملسٹ سنس (معیاری)',
    description: 'Contemporary geometric grotesk sans-serif, neutral balanced Urdu grotesk, clean open line-height.',
    badge: 'Layout 3 · Standard Modern Sans',
    fontFamilyClass: 'font-sans',
    headingStyle: 'font-sans font-extrabold tracking-tight',
    urduStyle: 'font-urdu font-bold tracking-normal',
    subtextStyle: 'font-sans font-normal tracking-normal text-slate-400',
    priceStyle: 'font-sans font-black tabular-nums',
  },
  {
    id: 'premium-bistro-mono',
    nameEn: 'Premium Bistro Monospace',
    nameUr: 'پریمیم بسٹرو مونو سپیس',
    description: 'Artisanal tabular monospace numerical accents, crisp architectural lettering, structured Urdu spacing.',
    badge: 'Layout 4 · Architectural Bistro Mono',
    fontFamilyClass: 'font-mono',
    headingStyle: 'font-mono font-bold tracking-wider uppercase',
    urduStyle: 'font-urdu font-bold tracking-wide',
    subtextStyle: 'font-mono font-normal tracking-wide text-xs',
    priceStyle: 'font-mono font-black tabular-nums',
  },
  {
    id: 'cyber-hybrid-roman',
    nameEn: 'Cyber Hybrid Roman',
    nameUr: 'سائبر ہائبرڈ رومن',
    description: 'Ultra-modern high-tech neo-grotesk with cybernetic uppercase styling, dynamic tracking and sharp Urdu accents.',
    badge: 'Layout 5 · High-Tech Cybernetic',
    fontFamilyClass: 'font-sans',
    headingStyle: 'font-sans font-black tracking-widest uppercase',
    urduStyle: 'font-urdu font-extrabold tracking-tight',
    subtextStyle: 'font-mono font-semibold tracking-wider text-xs',
    priceStyle: 'font-mono font-black tabular-nums text-amber-400',
  },
  {
    id: 'classic-regal-italic',
    nameEn: 'Classic Regal Food Italic',
    nameUr: 'کلاسک ریگل فوڈ اٹالک',
    description: 'Sophisticated warm italicized English food titles, regal curving Urdu strokes, sumptuous golden accents.',
    badge: 'Layout 6 · Regal Culinary Italic',
    fontFamilyClass: 'font-serif',
    headingStyle: 'font-serif italic font-extrabold tracking-tight',
    urduStyle: 'font-urdu font-bold tracking-normal leading-loose',
    subtextStyle: 'font-serif italic font-normal',
    priceStyle: 'font-serif font-black tabular-nums',
  },
];

// =========================================================================
// 9 SPECIFIC HIGH-CONTRAST TEXT COLOR PALETTES
// =========================================================================
export const TEXT_COLOR_PALETTES: TextColorPaletteConfig[] = [
  {
    id: 'charcoal-gold',
    nameEn: 'Deep Charcoal & Amber Gold',
    nameUr: 'چارکول اور امبر گولڈ',
    badge: 'Palette 1 · High Contrast Charcoal & Gold',
    titleColor: '#0F172A',
    headingColor: '#D97706',
    priceColor: '#B45309',
    urduColor: '#D97706',
    mutedColor: '#64748B',
    previewBg: '#FFFBEB',
  },
  {
    id: 'royal-emerald-cream',
    nameEn: 'Royal Emerald & Warm Cream',
    nameUr: 'شاہی زمردی اور ملائی',
    badge: 'Palette 2 · Imperial Jade & Mint',
    titleColor: '#064E3B',
    headingColor: '#059669',
    priceColor: '#10B981',
    urduColor: '#047857',
    mutedColor: '#065F46',
    previewBg: '#ECFDF5',
  },
  {
    id: 'crimson-flame',
    nameEn: 'Crimson Flame & Spice',
    nameUr: 'سرخ کرمسن اور تندوری مسالہ',
    badge: 'Palette 3 · Tandoori Crimson Flare',
    titleColor: '#881337',
    headingColor: '#E11D48',
    priceColor: '#BE123C',
    urduColor: '#9F1239',
    mutedColor: '#9F1239',
    previewBg: '#FFF1F2',
  },
  {
    id: 'midnight-contrast',
    nameEn: 'Pure Midnight High-Contrast',
    nameUr: 'خالص مڈنائٹ ہائی کنٹراسٹ',
    badge: 'Palette 4 · Stark Contrast Monochrome & Gold',
    titleColor: '#FFFFFF',
    headingColor: '#F8FAFC',
    priceColor: '#FACC15',
    urduColor: '#FBBF24',
    mutedColor: '#94A3B8',
    previewBg: '#09090B',
  },
  {
    id: 'warm-amber-espresso',
    nameEn: 'Warm Amber & Espresso',
    nameUr: 'وارم امبر اور ایسپریسو',
    badge: 'Palette 5 · Woodfire Espresso Roast',
    titleColor: '#451A03',
    headingColor: '#B45309',
    priceColor: '#D97706',
    urduColor: '#92400E',
    mutedColor: '#78350F',
    previewBg: '#FEF3C7',
  },
  {
    id: 'royal-sapphire-platinum',
    nameEn: 'Royal Sapphire & Platinum',
    nameUr: 'شاہی نیلم اور پلاٹینم',
    badge: 'Palette 6 · Deep Oceanic Navy',
    titleColor: '#0C4A6E',
    headingColor: '#0284C7',
    priceColor: '#0369A1',
    urduColor: '#0284C7',
    mutedColor: '#475569',
    previewBg: '#F0F9FF',
  },
  {
    id: 'terracotta-dune',
    nameEn: 'Balochi Terracotta & Dune',
    nameUr: 'بلوچی ٹیراکوٹا اور ریت',
    badge: 'Palette 7 · Desert Clay & Ochre',
    titleColor: '#7C2D12',
    headingColor: '#C2410C',
    priceColor: '#EA580C',
    urduColor: '#9A3412',
    mutedColor: '#9A3412',
    previewBg: '#FFEDD5',
  },
  {
    id: 'obsidian-neon-gold',
    nameEn: 'Obsidian & Neon Gold',
    nameUr: 'آبسیڈین اور نیون سنہری',
    badge: 'Palette 8 · Cyber Dark & Electric Gold',
    titleColor: '#FAFAFA',
    headingColor: '#FACC15',
    priceColor: '#F59E0B',
    urduColor: '#FDE047',
    mutedColor: '#A1A1AA',
    previewBg: '#18181B',
  },
  {
    id: 'velvet-plum-rose',
    nameEn: 'Rich Velvet Plum & Rose',
    nameUr: 'رچ مخمل پلم اور گلاب',
    badge: 'Palette 9 · Royal Velvet Wine & Pink',
    titleColor: '#4C0519',
    headingColor: '#BE123C',
    priceColor: '#E11D48',
    urduColor: '#9F1239',
    mutedColor: '#881337',
    previewBg: '#FDF2F8',
  },
];

// =========================================================================
// 5 DYNAMIC RAINBOW BUTTON ACCENT TEMPLATES + SYSTEM DEFAULT
// =========================================================================
export const BUTTON_THEMES: ButtonThemeConfig[] = [
  // 1. DEFAULT ACCENT: Emerald Green (#059669) & Soft Rose Pink (#FFEBEE) with Red Typography (#D32F2F)
  {
    id: 'default-emerald-rose',
    nameEn: 'Default Emerald & Soft Rose',
    nameUr: 'زمردی سبز اور نرم گلابی سرخ (ڈیفالٹ)',
    description: 'System standard: Soft Rose Pink (+Tray) with Red lettering & Emerald Green (Order Now) CTA.',
    badge: 'Default Core · Emerald & Soft Rose',
    trayBtnBg: '#FFEBEE',
    trayBtnText: '#D32F2F',
    trayBtnBorder: '1px solid #FFCDD2',
    orderBtnBg: '#059669',
    orderBtnText: '#FFFFFF',
    orderBtnBorder: 'none',
  },
  // 2. RAINBOW VARIANT 1: Rainbow Aurora Gleam
  {
    id: 'btn-rainbow-aurora',
    nameEn: 'Rainbow Aurora Gleam',
    nameUr: 'رینبو ارورا شفق چمک',
    description: 'Dynamic shifting rainbow gradient: Magenta to Cyan to Violet spectrum.',
    badge: 'Rainbow Button 1 · Aurora Spectrum',
    trayBtnBg: 'linear-gradient(135deg, #FF007A 0%, #7928CA 50%, #00DFD8 100%)',
    trayBtnText: '#FFFFFF',
    trayBtnBorder: 'none',
    orderBtnBg: 'linear-gradient(135deg, #00DFD8 0%, #7928CA 50%, #FF007A 100%)',
    orderBtnText: '#FFFFFF',
    orderBtnBorder: 'none',
    gradientStyle: 'linear-gradient(135deg, #FF007A 0%, #7928CA 50%, #00DFD8 100%)',
  },
  // 3. RAINBOW VARIANT 2: Electric Prism Chroma
  {
    id: 'btn-rainbow-prism',
    nameEn: 'Electric Prism Chroma',
    nameUr: 'الیکٹرک پرزم کروما',
    description: 'High-voltage prism transitioning through vivid Red, Gold, Violet, Royal Blue and Emerald.',
    badge: 'Rainbow Button 2 · Electric Prism',
    trayBtnBg: 'linear-gradient(135deg, #FF4D4D 0%, #F9CB28 35%, #7928CA 70%, #00F5A0 100%)',
    trayBtnText: '#FFFFFF',
    trayBtnBorder: 'none',
    orderBtnBg: 'linear-gradient(135deg, #00F5A0 0%, #4D79FF 35%, #7928CA 70%, #FF4D4D 100%)',
    orderBtnText: '#FFFFFF',
    orderBtnBorder: 'none',
    gradientStyle: 'linear-gradient(135deg, #FF4D4D 0%, #F9CB28 50%, #7928CA 100%)',
  },
  // 4. RAINBOW VARIANT 3: Royal Sunset Rainbow
  {
    id: 'btn-rainbow-sunset',
    nameEn: 'Royal Sunset Rainbow',
    nameUr: 'شاہی سن سیٹ رینبو',
    description: 'Warm incandescent spectrum blending Coral Pink, Golden Sunrise, and Violet Orchid.',
    badge: 'Rainbow Button 3 · Sunset Radiance',
    trayBtnBg: 'linear-gradient(135deg, #FA709A 0%, #FEE140 50%, #9B51E0 100%)',
    trayBtnText: '#FFFFFF',
    trayBtnBorder: 'none',
    orderBtnBg: 'linear-gradient(135deg, #9B51E0 0%, #FA709A 50%, #FEE140 100%)',
    orderBtnText: '#FFFFFF',
    orderBtnBorder: 'none',
    gradientStyle: 'linear-gradient(135deg, #FA709A 0%, #FEE140 50%, #9B51E0 100%)',
  },
  // 5. RAINBOW VARIANT 4: Holographic Opal Wave
  {
    id: 'btn-rainbow-opal',
    nameEn: 'Holographic Opal Wave',
    nameUr: 'ہولوگرافک اوپل لہر',
    description: 'Soft pastel holographic rainbow with mint, lavender, peach and pearlescent shine.',
    badge: 'Rainbow Button 4 · Holographic Opal',
    trayBtnBg: 'linear-gradient(135deg, #A8EDEA 0%, #FED6E3 40%, #FCCB90 100%)',
    trayBtnText: '#1E293B',
    trayBtnBorder: '1px solid rgba(255, 255, 255, 0.4)',
    orderBtnBg: 'linear-gradient(135deg, #D4FC79 0%, #96E6A1 50%, #A8EDEA 100%)',
    orderBtnText: '#0F172A',
    orderBtnBorder: 'none',
    gradientStyle: 'linear-gradient(135deg, #A8EDEA 0%, #FED6E3 50%, #D4FC79 100%)',
  },
  // 6. RAINBOW VARIANT 5: Neon Cyber Rainbow
  {
    id: 'btn-rainbow-neon',
    nameEn: 'Neon Cyber Rainbow',
    nameUr: 'نیون سائبر رینبو',
    description: 'High-contrast neon lime, electric cyan, vibrant purple and hot magenta.',
    badge: 'Rainbow Button 5 · Neon Cyber Wave',
    trayBtnBg: 'linear-gradient(135deg, #00FF87 0%, #60EFFF 35%, #B900FF 70%, #FF007A 100%)',
    trayBtnText: '#0A0A0A',
    trayBtnBorder: 'none',
    orderBtnBg: 'linear-gradient(135deg, #FF007A 0%, #B900FF 35%, #60EFFF 70%, #00FF87 100%)',
    orderBtnText: '#FFFFFF',
    orderBtnBorder: 'none',
    gradientStyle: 'linear-gradient(135deg, #00FF87 0%, #60EFFF 50%, #FF007A 100%)',
  },
];

